### PR TITLE
Fix `nullptr` access in `UMounteaDialogueManager`

### PR DESCRIPTION
**Pull request by Vivraan**
Addresses #5!

Also automatically formatted the whole file so maybe ignore those in the pull?

### CODE REVIEW

**Review by pavlicekdominik — CHANGES_REQUESTED** [review]
Those changes would cause the Player Participant dialogue rows to be unskippable.
A better fix would be to update `if (DialogueContext->ActiveDialogueParticipant.GetInterface() == nullptr)` to reflect the correct participant.

**Comment by Vivraan** [comment]
Okay, I'll add that extra null check.

**Comment by Vivraan** [comment]
Yes, but as it stands right now, no dialogue works since `ActiveDialogueParticipant` is null.

**Comment by pavlicekdominik** [comment]
> Yes, but as it stands right now, no dialogue works since `ActiveDialogueParticipant` is null.

If you don't have ActiveDialogueParticipant, then the problem is in a different place. 
Are you using GameplayTags feature? Or are you using only Nodes to find the correct participant?

**Comment by Vivraan** [comment]
> > Yes, but as it stands right now, no dialogue works since `ActiveDialogueParticipant` is null.
> 
> If you don't have ActiveDialogueParticipant, then the problem is in a different place. Are you using GameplayTags feature? Or are you using only Nodes to find the correct participant?

Both in some cases. The uses are not made clear enough I think.

I'll ask my client if it's okay for you to take a look at the code I'm making for them.

**Comment by Vivraan** [comment]
Find my details [here](http://vivraan.coolpage.biz).

**Comment by Kretoskar** [comment]
Hitting this issue right now. Why wasn't this merged?

**Comment by pavlicekdominik** [comment]
> Hitting this issue right now. Why wasn't this merged?

Because this commit request changed the logical flow of Active and Dialogue participant.

**Comment by pavlicekdominik** [comment]
> Hitting this issue right now. Why wasn't this merged?

Feel free to join support discord, as I don't have clear repro steps to reproduce this issue.
Discord link https://discord.gg/2vXWEEN

**Pull request closed without merging**
